[package]
name = "fancy"
version = "0.2.2"
edition = "2021"
authors = ["foxcirc"]
description = "Easily print colored text."
repository = "https://github.com/Foxcirc/fancy"
license = "MIT"
documentation = "https://docs.rs/fancy/latest/fancy/"

[lib]
proc-macro = true