[package]
name = "fancy"
version = "0.1.3"
edition = "2021"
authors = ["foxcirc"]
description = "Easily print string with color."
repository = "https://github.com/Foxcirc/fancy"
license = "MIT"

[lib]
proc-macro = true